/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class testndk_xhb_com_myndk_MyNdk */

#ifndef _Included_testndk_xhb_com_myndk_MyNdk
#define _Included_testndk_xhb_com_myndk_MyNdk
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     testndk_xhb_com_myndk_MyNdk
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_testndk_xhb_com_myndk_MyNdk_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
